include(Pkg.dir("AutomotiveDrivingModels", "test", "core", "test_utils.jl"))
include(Pkg.dir("AutomotiveDrivingModels", "test", "core", "test_curves.jl"))
include(Pkg.dir("AutomotiveDrivingModels", "test", "core", "test_roadways.jl"))
include(Pkg.dir("AutomotiveDrivingModels", "test", "core", "test_vehicles.jl"))
include(Pkg.dir("AutomotiveDrivingModels", "test", "core", "test_trajdatas.jl"))
include(Pkg.dir("AutomotiveDrivingModels", "test", "core", "test_scenes.jl"))